### ISSUE TITLE
ERROR in Patch_segmentation_baysor: Unable to find compatible target in cached code image. [Bug]

### ISSUE THREAD

**Issue by jmchan88** [gustaveroussy/sopa#42] opened 2024-03-29 14:24 UTC
Hi there, thanks so much for developing a great software!

I am running the cellpose_baysor.yaml config file for Xenium data, which is able to complete "cellpose resolve", but does crashes at the "patch_segmentation_baysor". I've been trying to run it starting from "checkpoint patchify_baysor" to no avail. What happens is that patchify works, and some of the baysor jobs do complete, but the rest crash with the following error: 

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=128000, mem_mib=122071, disk_mb=1000, disk_mib=954
Select jobs to execute...

[Tue Mar 26 19:42:35 2024]
rule patch_segmentation_baysor:
    input: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/patches_file_baysor, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10
    output: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10/segmentation_polygons.json, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10/segmentation_counts.loom
    jobid: 0
    reason: Forced execution
    wildcards: index=10
    resources: mem_mb=128000, mem_mib=122071, disk_mb=1000, disk_mib=954, tmpdir=/scratch/lsftmp/5002506.tmpdir

ERROR: Unable to find compatible target in cached code image.
Target 0 (cascadelake): Rejecting this target due to use of runtime-disabled features

[Tue Mar 26 19:42:35 2024]
Error in rule patch_segmentation_baysor:
    jobid: 0
    input: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/patches_file_baysor, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10
    output: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10/segmentation_polygons.json, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10/segmentation_counts.loom
    shell:

        if command -v module &> /dev/null; then
            module purge
        fi

        cd /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/10
        ~/.julia/bin/baysor run --save-polygons GeoJSON -c config.toml transcripts.csv :cell

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Any guidance whatsoever would be greatly appreciated! Thank you!

Joe

**Comment by quentinblampey** [comment] 2024-03-29 14:46
Hello @jmchan88,

It's difficult to know what happens without the Baysor error log (what you gave is the snakemake log, but not the actual rule error). If you use the Slurm profile, the logs are in the `sopa/workflow/logs` directory.
Else, can you show me your Snakemake command line (it may help me tell you where the log file is located)?

Just some guesses of potential errors:
- Out of memory error. In that case, two solutions: (i) you can reduce the `patch_width_microns` to run on smaller patches, or (ii) you can increase the required memory under `rule patch_segmentation_baysor` in the `sopa/workflow/Snakefile` file.
- This could also be related to this issue: #41 

Let me know, and I will be happy to help you!

**Comment by quentinblampey** [comment] 2024-03-29 16:39
Indeed the log file doesn't say much, and I'm not familiar with LSF clusters so I don't understand what is happening either.

Concerning the amount of transcripts, yes it is widely enough. But, since we make patches, it may happen that one patch is at the boundary of the slide and therefore contains very few transcripts. Can you check the `transcripts.csv` file under the `/data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/34` directory?

**Comment by jmchan88** [comment] 2024-03-29 18:30
Ah gotcha! I looked at the transcripts.csv file in this folder, which had:
42835 lines
292 unique values under "cell_id."

Would that explain the error? Thanks Quentin!
Joe

**Comment by jmchan88** [comment] 2024-03-29 19:36
Just to note, I have not done any interactive ROI selection in this pipeline (as I thought it was optional), so I do imagine that there could be patches that have no transcripts whatsoever .... is that an issue? Would this pipeline crash if there is a patch without any transcripts whatsoever?

**Comment by jmchan88** [comment] 2024-04-02 00:28
Just as an update, I found that each time I do a round of Patch_segmentation_baysor, a fraction of the patch jobs complete and another fraction crash. If I run sopa again though, it will run on the remaining unfinished patches. If I keep running sopa many times over, eventually all the patch jobs complete! But I wonder why a fraction of these patch jobs fail with the above error each time.

**Comment by quentinblampey** [comment] 2024-04-02 15:33
The amount of transcript you indicated should be enough, and the number of "prior" cells is also good. No, you don't need to run an ROI selection: we will simply not run Baysor on tiles with too few transcripts (if any)!

Concerning the fact that the runs sometimes crash and then succeed: it's weird to experience this kind of indeterminism. Since memory usage is not determinism, I think it really could be an "out of memory error", and this would also explain why the job crashes without any error logged.

Can you try to decrease the patch width in microns, and see if this behavior still happens?

**Comment by jmchan88** [comment] 2024-04-02 21:23
Hey Quentin! I tried to decrease the patch width in both microns and pixels in half, but the same problem still remains ... I don't get the sense that it's even getting a chance to run for some reason

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=200000, mem_mib=190735, disk_mb=1000, disk_mib=954
Select jobs to execute...

[Tue Apr  2 16:51:01 2024]
rule patch_segmentation_baysor:
    input: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/patches_file_baysor, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136
    output: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136/segmentation_polygons.json, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136/segmentation_counts.loom
    jobid: 0
    reason: Forced execution
    wildcards: index=136
    resources: mem_mb=200000, mem_mib=190735, disk_mb=1000, disk_mib=954, tmpdir=/scratch/lsftmp/5132942.tmpdir, partition=mononoke

ERROR: Unable to find compatible target in cached code image.
Target 0 (cascadelake): Rejecting this target due to use of runtime-disabled features

[Tue Apr  2 16:51:01 2024]
Error in rule patch_segmentation_baysor:
    jobid: 0
    input: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/patches_file_baysor, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136
    output: /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136/segmentation_polygons.json, /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136/segmentation_counts.loom
    shell:

        if command -v module &> /dev/null; then
            module purge
        fi

        cd /data/chanjlab/Xenium.lung.NE_plasticity.010124/preprocessing.fine/20231013__183137__JC_PILOT_RU151_RU263_RESECTION/output-XETG00065__0005504__RU151__20231013__183151.zarr/.sopa_cache/baysor_boundaries/136
        ~/.julia/bin/baysor run --save-polygons GeoJSON -c config.toml transcripts.csv :cell

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by quentinblampey** [comment] 2024-04-03 09:52
Ok, thanks for trying this. So maybe the Julia (or Baysor) installation has an issue. I found [this Julia issue](https://github.com/JuliaLang/julia/issues/48111) related to yours, did you already have a look?

Can you try to run Julia and/or Baysor without Sopa? Just to see if the issue is related to (i) Sopa, or (ii) Baysor, or even (iii) Julia itself.

**Comment by jmchan88** [comment] 2024-04-03 13:09
Hey Quentin! Thank you for pointing out that Github link, setting that environmental variable may be the answer! We are actually on the same wavelength, and I started running Julia Baysor last night directly at this step which preliminarily seems to work, but I'll keep you posted!

**Comment by quentinblampey** [comment] 2024-04-03 13:14
Great, thanks! If setting this variable works for Baysor/Julia, then you can try to add the variable directly in the `patch_segmentation_baysor` rule of the Snakefile

**Comment by jmchan88** [comment] 2024-04-03 19:18
Actually, I'm not sure if I'm understand the solution in the Julia post. Is the solution to go into Julia and type `ENV["JULIA_CPU_TARGET"] = "generic; native"`

**Comment by jmchan88** [comment] 2024-04-03 19:33
As another query, in trying to run julia baysor directly per patch, I ran the command in the Snakefile

`/home/chanj3/anaconda3/envs/sopa/bin/snakemake --profile lsf --config data_path=$mdir --configfile=/home/chanj3/chanjlab/shared/sopa/workflow/config/xenium/cellpose_baysor.yaml --use-conda`

However, this command doesn't seem to create the output json and loom files that would allow me to continue running the sopa snakemake pipeline after running Julia Baysor directly. How are these output files below created?

```
        f"{paths.smk_baysor_temp_dir}/{{index}}/segmentation_polygons.json",
        f"{paths.smk_baysor_temp_dir}/{{index}}/segmentation_counts.loom",
```

**Comment by quentinblampey** [comment] 2024-04-04 07:40
The `ENV["JULIA_CPU_TARGET"] = "generic; native"` line has to be run inside Julia, which is not very convenient for what we want to do. Instead, you can run `export JULIA_CPU_TARGET="generic; native"` in your shell.

For instance you can modify the `patch_segmentation_baysor` rule as below:

```
rule patch_segmentation_baysor:
    input:
        patches_file = paths.smk_patches_file_baysor,
        baysor_patch = f"{paths.smk_baysor_temp_dir}/{{index}}",
    output:
        f"{paths.smk_baysor_temp_dir}/{{index}}/segmentation_polygons.json",
        f"{paths.smk_baysor_temp_dir}/{{index}}/segmentation_counts.loom",
    params:
        args_baysor_prior_seg = args.baysor_prior_seg,
    resources:
        mem_mb=64_000,
    shell:
        """
        if command -v module &> /dev/null; then
            module purge
        fi

        export JULIA_CPU_TARGET="generic; native"

        cd {input.baysor_patch}
        {config[executables][baysor]} run --save-polygons GeoJSON -c config.toml transcripts.csv {params.args_baysor_prior_seg}
        """
```

Concerning your last comment, I'm not sure but can you try to add `--rerun-triggers params` to the snakemake command? It should re-run only the jobs whose params changed.

> NB: just in case you pull the latest changes from `sopa`, please upgrade the dependencies via `pip install -e . --upgrade` or `pip install sopa --upgrade`, else it will not be consistent with the latest changes

**Comment by jmchan88** [comment] 2024-04-05 18:29
Thanks Quentin! It's quite strange  ... with the new sopa version, even if I set the JULIA_CPU_TARGET to generic; native, there are random cases where I get the same error and julia baysor still seems to have JULIA_CPU_TARGET set to cascadelake

**Comment by quentinblampey** [comment] 2024-04-08 09:23
Just to be sure, Julia and Baysor work fine on their own? It breaks only when running Snakemake, is that correct?

**Comment by jmchan88** [comment] 2024-04-08 13:03
I think there’s some issue with some of the nodes on my LSF cluster … some
insist on using JULIA_CPU_TARGET of cascadelake despite me setting the
environmental variable otherwise

**Comment by quentinblampey** [comment] 2024-04-08 13:15
Okay, I see. Then, if it's specific to your cluster, I'll close the issue
Don't hesitate to re-open if needed! And let me know if you find a solution, I'm interested to see how to fix it, and it can help other users :)

**Closed by quentinblampey** 2024-04-08 13:15 UTC
