### ISSUE TITLE
[Bug] Issue with transcripts patches

### ISSUE THREAD

**Issue by lguerard** [gustaveroussy/sopa#134] opened 2024-10-03 12:04 UTC
Hi again and sorry to add more 😅 

## Description
During the patches creation for Baysor, some CSV files have issues and are incorrectly parsed resulting in errors later in the pipeline.
When opening one of the patches CSV, a couple of lines show 
![image](https://github.com/user-attachments/assets/23e2b8cc-c267-4e13-9241-2f2f4d5c1f48)

I tried seeing how to access the raw data to understand the issue, but there isn't enough information to  find it back.

## Reproducing the issue
Unfortunately, this is happening only on some patches and no reproducibly. Running twice the patches creation ended up with the same issue but on different patches :/

## Expected behavior
All transcripts should have all the columns in all patches.

## System
 - OS: Windows
 - Python version 3.10

I got this issue with both the `sopa2` branch and the `main` one.

**Comment by quentinblampey** [comment] 2024-10-14 07:12
Hi @lguerard, it seems to be the same issue as #123, can you confirm it?
I'm working on this already, but I couldn't reproduce it yet...

**Comment by lguerard** [comment] 2024-10-14 07:45
Ah yes, that seems to be simiar, something weird happening when creating the transcripts.csv for the patches..

**Comment by quentinblampey** [comment] 2024-10-14 07:58
Ok, then I'm closing this issue, and I'll continue on the other issue.

This is definitely a highly important issue, so I'll try to fix it quickly!
I never experienced this issue though, and I wasn't able to reproduce it. I suspect it may be a Windows-specific issue.

**Closed by quentinblampey** 2024-10-14 07:58 UTC
